// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace AnXin {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources_zh_Hans {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources_zh_Hans() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("AnXin.AppResources_zh_Hans", typeof(AppResources_zh_Hans).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string MasterPassword {
            get {
                return ResourceManager.GetString("MasterPassword", resourceCulture);
            }
        }
        
        internal static string NewUser {
            get {
                return ResourceManager.GetString("NewUser", resourceCulture);
            }
        }
        
        internal static string CreateMasterPassword {
            get {
                return ResourceManager.GetString("CreateMasterPassword", resourceCulture);
            }
        }
        
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        internal static string SendPasswordToYourEmail {
            get {
                return ResourceManager.GetString("SendPasswordToYourEmail", resourceCulture);
            }
        }
        
        internal static string YourEmailAddress {
            get {
                return ResourceManager.GetString("YourEmailAddress", resourceCulture);
            }
        }
        
        internal static string MaxChars {
            get {
                return ResourceManager.GetString("MaxChars", resourceCulture);
            }
        }
        
        internal static string MasterPasswordSet {
            get {
                return ResourceManager.GetString("MasterPasswordSet", resourceCulture);
            }
        }
        
        internal static string MasterPasswordSetDesc {
            get {
                return ResourceManager.GetString("MasterPasswordSetDesc", resourceCulture);
            }
        }
        
        internal static string NoInternetConnection {
            get {
                return ResourceManager.GetString("NoInternetConnection", resourceCulture);
            }
        }
        
        internal static string NavHome {
            get {
                return ResourceManager.GetString("NavHome", resourceCulture);
            }
        }
        
        internal static string NavAddEntry {
            get {
                return ResourceManager.GetString("NavAddEntry", resourceCulture);
            }
        }
        
        internal static string NavLogout {
            get {
                return ResourceManager.GetString("NavLogout", resourceCulture);
            }
        }
        
        internal static string FormAccountName {
            get {
                return ResourceManager.GetString("FormAccountName", resourceCulture);
            }
        }
        
        internal static string FormUserName {
            get {
                return ResourceManager.GetString("FormUserName", resourceCulture);
            }
        }
        
        internal static string FormPassword {
            get {
                return ResourceManager.GetString("FormPassword", resourceCulture);
            }
        }
        
        internal static string FormSave {
            get {
                return ResourceManager.GetString("FormSave", resourceCulture);
            }
        }
        
        internal static string FormUpdate {
            get {
                return ResourceManager.GetString("FormUpdate", resourceCulture);
            }
        }
        
        internal static string FormDelete {
            get {
                return ResourceManager.GetString("FormDelete", resourceCulture);
            }
        }
        
        internal static string characters {
            get {
                return ResourceManager.GetString("characters", resourceCulture);
            }
        }
        
        internal static string notes {
            get {
                return ResourceManager.GetString("notes", resourceCulture);
            }
        }
        
        internal static string featureNote1 {
            get {
                return ResourceManager.GetString("featureNote1", resourceCulture);
            }
        }
        
        internal static string featureNote2 {
            get {
                return ResourceManager.GetString("featureNote2", resourceCulture);
            }
        }
        
        internal static string featureNote3 {
            get {
                return ResourceManager.GetString("featureNote3", resourceCulture);
            }
        }
        
        internal static string featureNote4 {
            get {
                return ResourceManager.GetString("featureNote4", resourceCulture);
            }
        }
        
        internal static string featureNote5 {
            get {
                return ResourceManager.GetString("featureNote5", resourceCulture);
            }
        }
    }
}
